-- MySQL Script generated by MySQL Workbench
-- Tue Apr 21 12:33:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Rent_Movie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rent_Movie
-- -----------------------------------------------------
CREATE DATABASE Rent_Movie DEFAULT CHARACTER SET utf8 ;
USE Rent_Movie ;

-- -----------------------------------------------------
-- Table `Rent_Movie`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE  Rent_Movie.Usuario (
  id_usuario INT UNSIGNED NOT NULL,
  nome VARCHAR(45) NULL,
  cpf DECIMAL NOT NULL,
  data_birth DATETIME NULL,
  sexo VARCHAR(20) NULL,
  PRIMARY KEY (id_usuario))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Rent_Movie`.`Filme`
-- -----------------------------------------------------
CREATE TABLE Rent_Movie.Filme (
  id_filme INT UNSIGNED NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NULL,
  genero VARCHAR(255) NULL,
  diretor VARCHAR(255) NULL,
  quantidade VARCHAR(45) NULL,
  PRIMARY KEY (id_filme))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Rent_Movie`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE Rent_Movie.Locacao (
  idLocacao INT NOT NULL AUTO_INCREMENT,
  data_locacao DATETIME NOT NULL,
  data_devolucao DATETIME NOT NULL,
  fk_id_usuario INT(20) NULL,
  fk_id_filme INT(20) NULL,
  PRIMARY KEY (idLocacao))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

